os:
    #    - osx
    - linux
dist: trusty
sudo: false
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
- export PATH="$HOME/miniconda/bin:$PATH"
- bash miniconda.sh -b -p $HOME/miniconda
- conda config --set always_yes yes --set changeps1 no
- conda update -y -q conda
script:
- conda install -c uvcdat/label/nightly -c conda-forge -c uvcdat "vtk-cdat" cdutil genutil dv3d "mesalib>17" nose image-compare flake8 matplotlib
- export UVCDAT_ANONYMOUS_LOG=False
- echo $TRAVIS_BRANCH
- export TRAVIS_PR_BRANCH=$TRAVIS_BRANCH
- echo $TRAVIS_EVENT_TYPE
- echo $TRAVIS_PULL_REQUEST
- python setup.py install --old-and-unmanageable
- git clone git://github.com/uv-cdat/uvcdat-testdata
- cd uvcdat-testdata ; git checkout $TRAVIS_BRANCH ; cd ..
- df -h
- pip install dropbox
- python run_tests.py -n 1 -v2 -g --no-vtk-ui
after_success:
    - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then conda install conda-build && conda install anaconda-client && bash scripts/conda_upload.sh ; fi
